apiVersion: v1
kind: PersistentVolume
metadata:
  name: nimbus-sonarr-tv-share
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarr-tv-storageclass
  nfs:
    path: /volume1/media/tv
    server: 192.168.1.15