apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1000Gi
  storageClassName: sonarr-tv-storageclass