apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzb-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 0.1Gi
  storageClassName: sonarr-config-storageclass