apiVersion: v1
kind: PersistentVolume
metadata:
  name: nimbus-plex-share
spec:
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nimbus-plex-storageclass
  nfs:
    path: /volume1/media
    server: 192.168.1.15