apiVersion: v1
kind: PersistentVolume
metadata:
  name: nimbus-radarr-config-share
spec:
  capacity:
    storage: 0.1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: radarr-config-storageclass
  nfs:
    path: /volume1/nfs/media/radarr/config
    server: 192.168.1.15