apiVersion: v1
kind: PersistentVolume
metadata:
  name: nimbus-radarr-downloads-share
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: radarr-downloads-storageclass
  nfs:
    path: /volume1/nfs/media/radarr/downloads
    server: 192.168.1.15