apiVersion: v1
kind: PersistentVolume
metadata:
  name: nimbus-radarr-movies-share
spec:
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: radarr-movies-storageclass
  nfs:
    path: /volume1/media/movies
    server: 192.168.1.15