apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzb-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3000Gi
  storageClassName: radarr-movies-storageclass