apiVersion: v1
kind: PersistentVolume
metadata:
  name: nimbus-nzbget-config-share
spec:
  capacity:
    storage: 0.1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nimbus-nzbget-config-storageclass
  nfs:
    path: /volume1/nfs/media/nzbget
    server: 192.168.1.15