apiVersion: v1
kind: PersistentVolume
metadata:
  name: nimbus-nzbget-downloads-share
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nimbus-nzbget-downloads-storageclass
  nfs:
    path: /volume1/nfs/media/nzbget/downloads
    server: 192.168.1.15