apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nzbget-downloads
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: nimbus-nzbget-downloads-storageclass