apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nzbget-config
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2.5Gi
  storageClassName: nimbus-nzbget-config-storageclass